version: '3'
services:
  app:
    container_name: dbo-be
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 9000:9000
    env_file:
      - .env
    depends_on:
      - postgresdb
    networks:
      - dbo

  postgresdb:
    image: postgres:14-alpine
    container_name: dbo_postgres
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - '5432:5432'
    volumes:
      - database_posgresql:/var/lib/postgresql/data
    networks:
      - dbo

volumes:
  database_posgresql:

# Networks to be created to facilitate communication between containers
networks:
  dbo:
    driver: bridge
